### ISSUE TITLE
Wasting my time

### ISSUE THREAD

**Issue by galastrategic** [hossain-khan/SQLDelight-PostgreSQL-JVM-sample#13]
Look, I've been trying to get any working example at all going on my rig. I go to the sqldelight docs. It's missing so much. Nothing about their documentation makes any sense. They have skipped so many steps. So I'm looking to ANY working example. Sparse. I stumbled on yours. It does not work. I get no sane errors in the build output in IntelliJ.

I've downloaded your repo, renamed the sample file, installed postgresql. What the hell am I supposed to do to get this to work?

```
ERROR: 'void com.alecstrong.sql.psi.core.SqlFileBase.<init>(com.intellij.psi.FileViewProvider, com.intellij.lang.Language, java.util.Collection, int, kotlin.jvm.internal.DefaultConstructorMarker)'
```

Does that error make ANY sense to you at all?

I see red in the file

![image](https://github.com/hossain-khan/SQLDelight-PostgreSQL-JVM-sample/assets/143426688/bf2d592a-9008-4607-8967-399c13d42b2f)

Where in this code is there a 'PlayerQueries' ? Did you forget to commit files or something? I can't make sense of why this library is in active development yet they can't manage to have complete, sane docs for people to use what they've spent so much time on.

**Comment by hossain-khan** [comment]
@emergentcomplex Sorry, I saw this message bit later. Not sure if you have resolved the issue.

It's possible you are in the right track. The `PlayerQueries` is auto generated by the SQL delight file [Player.sq](https://github.com/hossain-khan/SQLDelight-PostgreSQL-JVM-sample/blob/main/src/main/sqldelight/dev/hossain/postgresqldelight/Player.sq)

Once you build the project, it should have the file available. I can double check gain.

**Comment by hossain-khan** [comment]
I have verified, after opening the project you just have to build, so that the SQLDelight interface and implementation is created.


Here are some screenshot for future reference

1. It's expected to have `PlayerQueries` missing after you open the project. 
![Screenshot 2024-06-16 080721](https://github.com/hossain-khan/SQLDelight-PostgreSQL-JVM-sample/assets/99822/14a9b626-1663-4a13-b3b0-00017def2ed1)

2. Use `Build Project` that generates those files.
![Screenshot 2024-06-16 080735](https://github.com/hossain-khan/SQLDelight-PostgreSQL-JVM-sample/assets/99822/6eb3d2e6-44f8-40ac-8ef7-455df5a90709)


3. After build, it will complile
![Screenshot 2024-06-16 080825](https://github.com/hossain-khan/SQLDelight-PostgreSQL-JVM-sample/assets/99822/1b3fd4b9-ad03-413c-8392-bc8ab66b53b5)

4. You can even open the generated content.
![Screenshot 2024-06-16 080845](https://github.com/hossain-khan/SQLDelight-PostgreSQL-JVM-sample/assets/99822/bf238d35-d43f-4aa6-ad9f-43337d3a3061)

Hope this helps @emergentcomplex
